# Generated by Django 2.1.7 on 2019-04-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAvailability', models.BooleanField(default=True)),
                ('userMessagable', models.BooleanField(default=True)),
                ('lastSeen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authorName', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=250)),
                ('publishDate', models.CharField(max_length=250)),
                ('bookPhoto', models.CharField(default='defaultBook.jpg', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(default=0)),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_1', models.CharField(default='nothing', max_length=250)),
                ('state_2', models.CharField(default='nothing', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='nothing', max_length=250)),
                ('dateOfAction', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('state', models.CharField(default='nothing', max_length=250)),
                ('match_date', models.DateField()),
                ('giving_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giving_book', to='bookclub_server.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.CharField(max_length=250)),
                ('messageDate', models.DateField()),
                ('isSeen', models.BooleanField(default=False)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_id', to='bookclub_server.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionInformation', models.CharField(max_length=250)),
                ('suggestionDate', models.DateField()),
                ('recommendation_score', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Book')),
            ],
        ),
        migrations.CreateModel(
            name='TradeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givingBook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givingBook_id', to='bookclub_server.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=250)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('onlineState', models.BooleanField(default=True)),
                ('profilePicture', models.CharField(default='default.jpg', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to='bookclub_server.User')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='bookclub_server.User')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User')),
            ],
        ),
        migrations.AddField(
            model_name='tradelist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='matched_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='wanted_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wanted_book', to='bookclub_server.Book'),
        ),
        migrations.AddField(
            model_name='history',
            name='match_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_id', to='bookclub_server.Match'),
        ),
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_1', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_2', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='bookrating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User'),
        ),
    ]
