# Generated by Django 2.1.7 on 2019-04-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(default=0)),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(default=0)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to='bookclub_server.User')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='bookclub_server.User')),
            ],
        ),
    ]
