# Generated by Django 2.1.7 on 2019-04-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='matchDate',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestionDate',
            new_name='suggestion_date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matchInformation',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_id1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user_id2',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestionInformation',
        ),
        migrations.AddField(
            model_name='match',
            name='giving_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giving_book', to='bookclub_server.Book'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='matched_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='wanted_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wanted_book', to='bookclub_server.Book'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='giving_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giving_book_suggestion', to='bookclub_server.Book'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='state',
            field=models.CharField(default='nothing', max_length=250),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_user', to='bookclub_server.User'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='wanted_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wanted_book_suggestion', to='bookclub_server.Book'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_suggestion', to='bookclub_server.User'),
        ),
    ]
