# Generated by Django 2.1.7 on 2019-04-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0002_auto_20190427_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='match_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Match'),
        ),
    ]
