# Generated by Django 2.1.7 on 2019-04-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0002_remove_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='matchConfirmation_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='matchRejection_id',
        ),
        migrations.AddField(
            model_name='history',
            name='match_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_id', to='bookclub_server.Match'),
        ),
        migrations.AddField(
            model_name='history',
            name='state',
            field=models.CharField(default='nothing', max_length=250),
        ),
    ]
