# Generated by Django 2.1.7 on 2019-04-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0002_bookrating_userrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelist',
            name='wantedBook_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
