# Generated by Django 2.1.7 on 2019-04-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0003_chat_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggested_book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_book', to='bookclub_server.Book'),
        ),
    ]
