# Generated by Django 2.1.7 on 2019-04-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0003_auto_20190409_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='state_1',
            field=models.CharField(default='nothing', max_length=250),
        ),
        migrations.AddField(
            model_name='chat',
            name='state_2',
            field=models.CharField(default='nothing', max_length=250),
        ),
    ]
