# Generated by Django 2.1.7 on 2019-04-30 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0004_suggestion_suggested_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='suggestion_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Suggestion'),
        ),
        migrations.AddField(
            model_name='history',
            name='suggestion_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_id', to='bookclub_server.Suggestion'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='match_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclub_server.Match'),
        ),
        migrations.AlterField(
            model_name='history',
            name='match_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_id', to='bookclub_server.Match'),
        ),
    ]
