# Generated by Django 2.1.7 on 2019-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0005_suggestion_recommendation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
