# Generated by Django 2.0.5 on 2019-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub_server', '0006_auto_20190409_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='raiting',
            new_name='rating',
        ),
    ]
